learning_Templates/basic_app/urls.py
from django.conf import Path
from basic_app import views
from django.urls import path

app_name = 'basic_app'

urlpatterns = [
    path('relative/', views.relative, name='relative'),
    path('other/', views.other, name='other'),
]

learning_Templates/learning_Templates/urls.py
from django.contrib import admin
from django.urls import path, include
from basic_app import views

urlpatterns = [
    path('', views.index, name="index"),
    path('admin/', admin.site.urls),
    path('basic_app/', include('basic_app.urls')),
]

learning_Templates/basic_app/models.py
from django.db import models

# Create your models here.

learning_Templates/basic_app/views.py
from django.shortcuts import render


# Create your views here.
def index(request):
    context_dict = {'text': 'hello world', 'number': 100}
    return render(request, 'basic_app/index.html', context_dict)


def other(request):
    return render(request, 'basic_app/other.html')


def relative(request):
    return render(request, 'basic_app/relative_url_templates.html')

learning_Templates/templates/basic_app/base.html
<!doctype html>
<html lang="en">
<head>
    {% load static %}
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Document</title>
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
</head>
<body>
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
      <div class="navbar-nav">
        <a class="navbar-brand" href="{% url 'index' %}">DJANGO</a>
        <a class="nav-item nav-link" href="{% url 'admin:index' %}">Admin</a>
        <a class="nav-item nav-link" href="{% url 'basic_app:other' %}">Other</a>
          <a class="nav-item nav-link" href="{% url 'basic_app:relative' %}">Relative</a>
      </div>
    </nav>

    <div class="container">
    {% block body_block %}
    <!--    Anything outside of this will be inherited if you use extend-->
    {% endblock %}
    </div>
</body>
</html>

learning_Templates/templates/basic_app/index.html
<!doctype html>
{% extends "basic_app/base.html" %}
    {% block body_block%}
        {% load my_extras %}
        <h1>Welcome to Index</h1>
        <h1>{{ text | cutter:'hello' }}</h1>
        <h1>{{ number | add:"99" }}</h1>
    {% endblock %}

learning_Templates/templates/basic_app/other.html
<!doctype html>
{% extends "basic_app/base.html"%}
    {%block body_block%}
    <h1>Welcome to Other</h1>
    {%endblock%}

learning_Templates/templates/basic_app/relative_url_templates.html
<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Document</title>
</head>
<body>
    <h1>Welcome to Relative urls templates</h1>
    <a href="{% url 'basic_app:other' %}">THE OTHER PAGE</a>
    <p></p>
    <a href="{% url 'admin:index' %}">Admin</a>
<p>
    <a href="{% url 'index'%}">Index</a>
</p>
</body>
</html>